# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-cba-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-cba
  template:
    metadata:
      labels:
        app: chatbot-cba
    spec:
      initContainers:
        - name: init-copy-videos
          image: chatbot-cba:latest
          command: ['sh', '-c', 'cp /app/videos.json /app/data/videos.json']
          volumeMounts:
            - name: videos-storage
              mountPath: /app/data
      containers:
        - name: chatbot-cba
          image: chatbot-cba:latest
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: chatbot-secrets
                  key: OPENAI_API_KEY
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: chatbot-secrets
                  key: TELEGRAM_BOT_TOKEN
          volumeMounts:
            - name: videos-storage
              mountPath: /app/data
      volumes:
        - name: videos-storage
          persistentVolumeClaim:
            claimName: videos-pvc