apiVersion: v1
kind: Service
metadata:
  name: chatbot-cba-service
spec:
  selector:
    app: chatbot-cba
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  # The port your Flask app is running on
  type: NodePort